import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Spotify Web Player",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="antialiased scroll-smooth">
      <body
        className={`${GeistSans.className} bg-zinc-900 selection:bg-zinc-600/25`}
      >
        {children}

        <Toaster
          toastOptions={{
            classNames: {
              toast: "bg-zinc-900/50 border-0 text-zinc-200 gap-2",
            },
          }}
        />
      </body>
    </html>
  );
}
