import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata = {
  title: "Spotify Web Player",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="antialiased scroll-smooth">
      <body
        className={`${GeistSans.className} bg-zinc-900 selection:bg-zinc-600/25`}
      >
        {children}
      </body>
    </html>
  );
}
